### PR TITLE
fix race in Disconnect

### PR DESCRIPTION
**Pull request by serbaut**

### CODE REVIEW

**Comment by gmallard** [comment]
Thanks for your effort, and I will look at this.

Before looking I will comment that the description make me think this might be related to these discussions:

https://github.com/gmallard/stompngo/issues/25

and

https://github.com/gmallard/stompngo_examples/issues/2

**Comment by gmallard** [comment]
Please add a failing test, as you show in the initial problem description.

**Comment by serbaut** [comment]
I don't think I can write a failing test without modifying reader() as show in https://github.com/gmallard/stompngo/issues/27

**Comment by gmallard** [comment]
Yes, I see that now that I look closely.

How did you see this problem in the first place ?

**Comment by serbaut** [comment]
This happens for us in our live environments occasionally.

**Comment by gmallard** [comment]
Real tests of this library are done by:

```
go test -v
```

What you need to run that is:

- A running broker on 'localhost'
- Listening on port 61613

With this fix applied, I consistently get:

```
...
...
=== RUN   TestBytes1
panic: send on closed channel

goroutine 131 [running]:
panic(0x5840e0, 0xc4200a9030)
	/ad3/gma/gorepo/github/go/src/runtime/panic.go:500 +0x1a1
github.com/gmallard/stompngo.(*Connection).handleReadError(0xc420070900, 0xc4200c4d0c, 0x0, 0xc4200ab980, 0x2, 0x2, 0x6929c8, 0x0, 0x0, 0x660740, ...)
	/ad3/gma/gosrc/src/github.com/gmallard/stompngo/connection.go:224 +0x17f
github.com/gmallard/stompngo.(*Connection).reader(0xc420070900)
	/ad3/gma/gosrc/src/github.com/gmallard/stompngo/reader.go:40 +0x7ea
created by github.com/gmallard/stompngo.Connect
	/ad3/gma/gosrc/src/github.com/gmallard/stompngo/connect.go:111 +0x878
exit status 2
FAIL	github.com/gmallard/stompngo	0.369s
```

I also believe there is a subtle race in this part of processing.  BUt I do not think what you show it the fix.

**Comment by gmallard** [comment]
I merged this PR, along with another small tweak.  See:

6401ad7

b7c31d4

Both on 'dev' branch, and will be merged to 'master' later.

**Pull request merged**
