### PR TITLE
 bugfix: race condition of disconnecting connection when it goes down

### PR DESCRIPTION
**Pull request by itomsawyer**

### CODE REVIEW

**Comment by itomsawyer** [comment]
Issue https://github.com/gmallard/stompngo/issues/42

**Comment by gmallard** [comment]
Hi - With that code I get one test failure:

```
[gmallard@tjjackson stompngo (itscs)]$ go test -v -run TestConnCDDiscStompDiscReceipt
=== RUN   TestConnCDDiscStompDiscReceipt
--- FAIL: TestConnCDDiscStompDiscReceipt (0.05s)
	conndisc_test.go:158: TestConnCDDiscStompDiscReceipt Expected receipt-id, not received
FAIL
exit status 1
FAIL	github.com/gmallard/stompngo	0.053s
```

Please get that fixed, and I will run more tests.

**Comment by itomsawyer** [comment]
@gmallard  Here's the update of this PR:

1. Update readme.md : Point out where testing with rabbitmq-stomp , STOMP_RMQ must be set. 
2. Error response of connect frame is returned to top level which is useful for debug.
3. Fix TestConnCDDiscStompDiscReceipt failed.

**Comment by gmallard** [comment]
Thank you for your efforts here.

**Comment by itomsawyer** [comment]
My pleasure.

**Pull request merged**
